*.sink.file.class=org.apache.hadoop.metrics2.sink.FileSink
*.sink.file.filename=/opt/hadoop/logs/metrics.log
*.sink.file.period=10

*.sink.graphite.class=org.apache.hadoop.metrics2.sink.GraphiteSink
*.sink.graphite.server.host=localhost
*.sink.graphite.server.port=2003
*.sink.graphite.prefix=hadoop
*.sink.graphite.period=60

datanode.sink.file.class=org.apache.hadoop.metrics2.sink.FileSink
datanode.sink.file.filename=/opt/hadoop/logs/datanode-metrics.log
datanode.sink.file.period=10

namenode.sink.file.class=org.apache.hadoop.metrics2.sink.FileSink
namenode.sink.file.filename=/opt/hadoop/logs/namenode-metrics.log
namenode.sink.file.period=10

journalnode.sink.file.class=org.apache.hadoop.metrics2.sink.FileSink
journalnode.sink.file.filename=/opt/hadoop/logs/journalnode-metrics.log
journalnode.sink.file.period=10
